Style/Documentation:
  Enabled: false

require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
