Style/Documentation:
  Enabled: false

require: rubocop-rspec

RSpec/NestedGroups:
  MaxNesting: 3

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
