sudo: false
language: ruby
rvm:
  - 2.3.0
before_install:
  - gem install bundler -v 1.11.2
notifications:
  email:
    on_success: never
script:
  - bundle exec rspec spec
  - bundle exec rubocop --display-cop-names
